version: '3.1'

services:
  neo4j:
    image: neo4j:latest
    container_name: IGD_Project_Neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_PLUGINS: "apoc,apoc-extended,graph-data-science,osm"
    volumes:
      - ./mnt/data:/data
      - ./mnt/conf/:/conf
      - ./mnt/var/lib/neo4j/plugins:/var/lib/neo4j/plugins
      - ./mnt/var/lib/neo4j/labs:/var/lib/neo4j/labs
      - ./mnt/import/:/import
    networks:
      - neo4j-network

networks:
  neo4j-network:
    driver: bridge
